djangolive/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'djangolive.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^forum/', include('forum.urls', namespace='forum')),
	#url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
)

forum/urls.py
from django.conf.urls import patterns, url

from forum import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^topico/(?P<topico_id>\d+)/$', views.visualizar_topico, name='topico'),
    url(r'^topico/(?P<topico_id>\d+)/comentar/$', views.comentar, name='comentar'),
    url(r'^categoria/(?P<categoria_id>\d+)/$', views.visualizar_categoria, name='categoria'),
    url(r'^categoria/(?P<categoria_id>\d+)/novo_topico/$', views.novo_topico, name='novo_topico'),
    url(r'^categoria/(?P<categoria_id>\d+)/novo_topico_criar/$', views.novo_topico_criar, name='novo_topico_criar'),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

forum/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Label(models.Model):
	nome = models.CharField(max_length=50)

	def __unicode__(self):
		return self.nome

class Categoria(models.Model):
	titulo = models.CharField(max_length=50)
	descricao = models.CharField(max_length=200)
	identificacao = models.CharField(max_length=20)
	categoria_pai = models.ForeignKey("self", blank=True, null=True)

class Topico(models.Model):
	autor = models.ForeignKey(User)
	data_hora_criacao = models.DateTimeField(auto_now_add=True)
	votos = models.IntegerField(blank=True, default=0)
	conteudo = models.CharField(max_length=2000, blank=False)
	labels = models.ManyToManyField(Label, blank=True)
	titulo = models.CharField(max_length=100)
	descricao = models.CharField(max_length=200, blank=True)
	categoria = models.ForeignKey(Categoria, blank=True, null=True)

class Post(models.Model):
	autor = models.ForeignKey(User)
	data_hora_criacao = models.DateTimeField(auto_now_add=True)
	votos = models.IntegerField(blank=True, default=0)
	conteudo = models.CharField(max_length=2000)
	topico = models.ForeignKey(Topico)

	def __unicode__(self):
		return self.conteudo


class UsuarioForum(models.Model):
	user = models.OneToOneField(User)
	topicos_acompanhados = models.ManyToManyField(Topico, blank=True)

	def __unicode__(self):
		return self.user.username

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

forum/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from forum.models import *
from django.core.urlresolvers import reverse

@login_required
def index(request):
	return render(request, 'forum/index.html', {
		    'categoria': None,
		    'categorias': Categoria.objects.filter(categoria_pai__isnull=True),
            'topicos': Topico.objects.filter(categoria__isnull=True)
        })

def visualizar_topico(request, topico_id):
	t = get_object_or_404(Topico, pk=topico_id)
	return render(request, 'forum/topico.html', {
			'topico': t
		})

def comentar(request, topico_id):
	t = get_object_or_404(Topico, pk=topico_id)
	t.post_set.create(conteudo=request.POST['conteudo'], autor=request.user)

	return HttpResponseRedirect(reverse('forum:topico', args=(t.id,)))

def visualizar_categoria(request, categoria_id):
	c = get_object_or_404(Categoria, pk=categoria_id)
	return render(request, 'forum/categoria.html', {
			'categoria': c,
		    'categorias': Categoria.objects.filter(categoria_pai=c),
            'topicos': Topico.objects.filter(categoria=c)
        })

def novo_topico(request, categoria_id):
	c = get_object_or_404(Categoria, pk=categoria_id)
	return render(request, 'forum/novo_topico.html', {
			'categoria': c
		})

def novo_topico_criar(request, categoria_id):
	c = get_object_or_404(Categoria, pk=categoria_id)
	t = c.topico_set.create(titulo=request.POST['titulo'], 
		descricao=request.POST['descricao'], 
		conteudo=request.POST['conteudo'],
		autor=request.user)
	return HttpResponseRedirect(reverse('forum:topico', args=(t.id,)))

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from polls.models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions, not including futures questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

forum/templates/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'forum/css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'forum/css/bootstrap-theme.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'forum/css/forum.css' %}" />
    <title>{% block title %}User test{% endblock %}</title>
</head>

<body class="body">
    <div id="header">
        {% block header %}
        header
        <a href="{% url 'forum:index'%}">Pagina Inicial</a>
	    {% endblock %}
    </div>

    <div id="content">
        {% block content %}
        content
        {% endblock %}
    </div>

    <div id="footer">
        {% block footer %}
        footer
        {% endblock %}
    </div>
</body>

</html>

forum/templates/forum/categoria.html
{% extends "base.html" %}


{% block content %}

<a href="{% url 'forum:novo_topico' categoria.id %}">Novo topico</a>

{% for categoria in categorias %}

<div class="row post">
  <div class="col-sm-12 post-header">
      <h1><a href="{% url 'forum:categoria' categoria.id %}">{{ categoria.titulo }}</a></h1>
      {{categoria.descricao}}
  </div>
</div>
{% endfor %}


{% for topico in topicos %}

<div class="row post">
  <div class="col-sm-12">
    <div class="col-sm-8 post-header">
      <p><a href="{% url 'forum:topico' topico.id %}">{{ topico.titulo }}</a></p>
      {{topico.descricao}}

    </div>
    <div class="col-sm-4 post-header">
        {{ topico.autor }}<br />
        {{ topico.data_hora_criacao }}
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}

forum/templates/forum/index.html
{% extends "base.html" %}


{% block content %}

{% for topico in topicos %}

<h1><a href="{% url 'forum:topico' topico.id %}">{{ topico.titulo }}</a></h1>
{{topico.descricao}}
<br />
{% endfor %}

{% endblock %}

forum/templates/forum/novo_topico.html
{% extends "base.html" %}

{% block content %}
<div class="row post">
<form action="{% url 'forum:novo_topico_criar' categoria.id %}" method="post">
{% csrf_token %}
    Título: <input type="text" name="titulo" /><br />
    Descrição: <input type="text" name="descricao" /><br />
    Conteúdo: <textarea name="conteudo" style="width: 500px; height: 200px"></textarea><br /> 
	  <input type="submit" value="Comentar" />
</form>
</div>
{% endblock%}

forum/templates/forum/topico.html
{% extends "base.html" %}


{% block content %}
<div class="row post">
  <div class="col-sm-12">
    <div class="row post-header">
      <h1>{{ topico.titulo }} </h1>
      <p>{{topico.descricao}}</p>
    </div>
    <div class="row">
      <div class="col-xs-8 col-sm-2">
        {{ topico.autor }}<br />
        {{ topico.data_hora_criacao }}
      </div>
      <div class="col-xs-4 col-sm-10">
        {{topico.conteudo|linebreaks}}
      </div>
    </div>
  </div>
</div>
{% for post in topico.post_set.all %}
<div class="row post">
  <div class="col-sm-12">
    <div class="row">
      <div class="col-xs-8 col-sm-2">
        {{ post.autor }}<br />
        {{ post.data_hora_criacao }}
      </div>
      <div class="col-xs-4 col-sm-10">
        {{post.conteudo|linebreaks}}
      </div>
    </div>
  </div>
</div>{% endfor %}

<div class="row post">
<form action="{% url 'forum:comentar' topico.id %}" method="post">
{% csrf_token %}
    <textarea name="conteudo" style="width: 500px; height: 200px"></textarea><br /> 
	  <input type="submit" value="Comentar" />
</form>
</div>

{% endblock %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>